### ISSUE TITLE
IP mongoose Validation

### ISSUE THREAD

**Issue by GreenPioneer** [andjosh/mongo-throttle#11]
I believe this to be a enterprise issue but still has merit to handle

`Validation Error: IP (12.243.243.23).`

That isnt the exact ip string because im not allowed to share that but you get the idea. 

Basically my point is lets add some error handling for validation on our Model so that it does not break any one system

**Comment by joshbeckman** [comment]
For reference, here is the regex being used for validation: https://github.com/sindresorhus/ip-regex/blob/master/index.js#L3

**Comment by GreenPioneer** [comment]
ValidationError: Path `ip` is invalid (97.79.186.199).

https://meanstackjs.herokuapp.com/

**Comment by GreenPioneer** [comment]
```(node:17) Warning: a promise was created in a handler at app/node_modules/mongoose/lib/query.js:2313:18 but was not returned from it, see http://goo.gl/rRqMUw
2016-11-29T20:32:29.673342+00:00 app[web.1]:     at new Promise (/app/node_modules/bluebird/js/release/promise.js:77:14)
2016-11-29T20:32:29.680431+00:00 app[web.1]: ValidationError: Path `ip` is invalid (97.79.186.199).
2016-11-29T20:32:29.680434+00:00 app[web.1]:     at MongooseError.ValidationError (/app/node_modules/mongoose/lib/error/validation.js:23:11)
2016-11-29T20:32:29.680435+00:00 app[web.1]:     at model.Document.invalidate (/app/node_modules/mongoose/lib/document.js:1473:32)
2016-11-29T20:32:29.680436+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/document.js:1349:17
2016-11-29T20:32:29.680437+00:00 app[web.1]:     at validate (/app/node_modules/mongoose/lib/schematype.js:705:7)
2016-11-29T20:32:29.680438+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/schematype.js:742:9
2016-11-29T20:32:29.680439+00:00 app[web.1]:     at Array.forEach (native)
2016-11-29T20:32:29.680440+00:00 app[web.1]:     at SchemaString.SchemaType.doValidate (/app/node_modules/mongoose/lib/schematype.js:710:19)
2016-11-29T20:32:29.680441+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/document.js:1347:9
2016-11-29T20:32:29.680441+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-11-29T20:32:29.680442+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-11-29T20:32:29.680442+00:00 app[web.1]: From previous event:
2016-11-29T20:32:29.680443+00:00 app[web.1]:     at model.wrappedPointCut [as save] (/app/node_modules/mongoose/lib/document.js:1961:21)
2016-11-29T20:32:29.680443+00:00 app[web.1]:     at /app/node_modules/mongo-throttle/lib/throttler.js:97:20
2016-11-29T20:32:29.680444+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/query.js:2313:18
2016-11-29T20:32:29.680445+00:00 app[web.1]:     at runCallback (timers.js:637:20)
2016-11-29T20:32:29.680446+00:00 app[web.1]:     at tryOnImmediate (timers.js:610:5)
2016-11-29T20:32:29.680446+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:582:5)```

**Comment by GreenPioneer** [comment]
ValidationError: Path `ip` is invalid (173.252.88.92).    at MongooseError.ValidationError (/app/node_modules/mongoose/lib/error/validation.js:23:11)    at model.Document.invalidate (/app/node_modules/mongoose/lib/document.js:1473:32)    at /app/node_modules/mongoose/lib/document.js:1349:17    at va...

**Comment by GreenPioneer** [comment]
i tried getting facebook to scrape a url and it wont go through. What are you thoughts @andjosh  on taking out model validation ? Cause if were still sourcing `(173.252.88.92). ` thats better than breaking the system

**Comment by joshbeckman** [comment]
I agree. Let's rip it out. :)
